// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v4.25.3
// source: api/v1/memo_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { FieldMask } from "../../google/protobuf/field_mask";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Direction, directionFromJSON, directionToJSON, State, stateFromJSON, stateToJSON } from "./common";
import { Node } from "./markdown_service";
import { Reaction } from "./reaction_service";
import { Resource } from "./resource_service";

export const protobufPackage = "memos.api.v1";

export enum Visibility {
  VISIBILITY_UNSPECIFIED = 0,
  PRIVATE = 1,
  PROTECTED = 2,
  PUBLIC = 3,
  UNRECOGNIZED = -1,
}

export function visibilityFromJSON(object: any): Visibility {
  switch (object) {
    case 0:
    case "VISIBILITY_UNSPECIFIED":
      return Visibility.VISIBILITY_UNSPECIFIED;
    case 1:
    case "PRIVATE":
      return Visibility.PRIVATE;
    case 2:
    case "PROTECTED":
      return Visibility.PROTECTED;
    case 3:
    case "PUBLIC":
      return Visibility.PUBLIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Visibility.UNRECOGNIZED;
  }
}

export function visibilityToJSON(object: Visibility): string {
  switch (object) {
    case Visibility.VISIBILITY_UNSPECIFIED:
      return "VISIBILITY_UNSPECIFIED";
    case Visibility.PRIVATE:
      return "PRIVATE";
    case Visibility.PROTECTED:
      return "PROTECTED";
    case Visibility.PUBLIC:
      return "PUBLIC";
    case Visibility.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Memo {
  /**
   * The name of the memo.
   * Format: memos/{memo}, memo is the user defined id or uuid.
   */
  name: string;
  state: State;
  /**
   * The name of the creator.
   * Format: users/{user}
   */
  creator: string;
  createTime?: Date | undefined;
  updateTime?: Date | undefined;
  displayTime?: Date | undefined;
  content: string;
  nodes: Node[];
  visibility: Visibility;
  tags: string[];
  pinned: boolean;
  resources: Resource[];
  relations: MemoRelation[];
  reactions: Reaction[];
  property?:
    | Memo_Property
    | undefined;
  /**
   * The name of the parent memo.
   * Format: memos/{id}
   */
  parent?:
    | string
    | undefined;
  /** The snippet of the memo content. Plain text only. */
  snippet: string;
  /** The location of the memo. */
  location?: Location | undefined;
}

export interface Memo_Property {
  hasLink: boolean;
  hasTaskList: boolean;
  hasCode: boolean;
  hasIncompleteTasks: boolean;
}

export interface Location {
  placeholder: string;
  latitude: number;
  longitude: number;
}

export interface CreateMemoRequest {
  /** The memo to create. */
  memo?: Memo | undefined;
}

export interface ListMemosRequest {
  /**
   * The parent is the owner of the memos.
   * If not specified or `users/-`, it will list all memos.
   */
  parent: string;
  /** The maximum number of memos to return. */
  pageSize: number;
  /**
   * A page token, received from a previous `ListMemos` call.
   * Provide this to retrieve the subsequent page.
   */
  pageToken: string;
  /**
   * The state of the memos to list.
   * Default to `NORMAL`. Set to `ARCHIVED` to list archived memos.
   */
  state: State;
  /**
   * What field to sort the results by.
   * Default to display_time.
   */
  sort: string;
  /**
   * The direction to sort the results by.
   * Default to DESC.
   */
  direction: Direction;
  /**
   * Filter is a CEL expression to filter memos.
   * Refer to `Shortcut.filter`.
   */
  filter: string;
  /**
   * [Deprecated] Old filter contains some specific conditions to filter memos.
   * Format: "creator == 'users/{user}' && visibilities == ['PUBLIC', 'PROTECTED']"
   */
  oldFilter: string;
}

export interface ListMemosResponse {
  memos: Memo[];
  /**
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   */
  nextPageToken: string;
}

export interface GetMemoRequest {
  /** The name of the memo. */
  name: string;
}

export interface UpdateMemoRequest {
  /**
   * The memo to update.
   * The `name` field is required.
   */
  memo?: Memo | undefined;
  updateMask?: string[] | undefined;
}

export interface DeleteMemoRequest {
  /** The name of the memo. */
  name: string;
}

export interface RenameMemoTagRequest {
  /**
   * The parent, who owns the tags.
   * Format: memos/{id}. Use "memos/-" to rename all tags.
   */
  parent: string;
  oldTag: string;
  newTag: string;
}

export interface DeleteMemoTagRequest {
  /**
   * The parent, who owns the tags.
   * Format: memos/{id}. Use "memos/-" to delete all tags.
   */
  parent: string;
  tag: string;
  deleteRelatedMemos: boolean;
}

export interface SetMemoResourcesRequest {
  /** The name of the memo. */
  name: string;
  resources: Resource[];
}

export interface ListMemoResourcesRequest {
  /** The name of the memo. */
  name: string;
}

export interface ListMemoResourcesResponse {
  resources: Resource[];
}

export interface MemoRelation {
  memo?: MemoRelation_Memo | undefined;
  relatedMemo?: MemoRelation_Memo | undefined;
  type: MemoRelation_Type;
}

export enum MemoRelation_Type {
  TYPE_UNSPECIFIED = 0,
  REFERENCE = 1,
  COMMENT = 2,
  UNRECOGNIZED = -1,
}

export function memoRelation_TypeFromJSON(object: any): MemoRelation_Type {
  switch (object) {
    case 0:
    case "TYPE_UNSPECIFIED":
      return MemoRelation_Type.TYPE_UNSPECIFIED;
    case 1:
    case "REFERENCE":
      return MemoRelation_Type.REFERENCE;
    case 2:
    case "COMMENT":
      return MemoRelation_Type.COMMENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MemoRelation_Type.UNRECOGNIZED;
  }
}

export function memoRelation_TypeToJSON(object: MemoRelation_Type): string {
  switch (object) {
    case MemoRelation_Type.TYPE_UNSPECIFIED:
      return "TYPE_UNSPECIFIED";
    case MemoRelation_Type.REFERENCE:
      return "REFERENCE";
    case MemoRelation_Type.COMMENT:
      return "COMMENT";
    case MemoRelation_Type.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface MemoRelation_Memo {
  /**
   * The name of the memo.
   * Format: memos/{id}
   */
  name: string;
  uid: string;
  /** The snippet of the memo content. Plain text only. */
  snippet: string;
}

export interface SetMemoRelationsRequest {
  /** The name of the memo. */
  name: string;
  relations: MemoRelation[];
}

export interface ListMemoRelationsRequest {
  /** The name of the memo. */
  name: string;
}

export interface ListMemoRelationsResponse {
  relations: MemoRelation[];
}

export interface ListMemoReactionsRequest {
  /** The name of the memo. */
  name: string;
}

export interface ListMemoReactionsResponse {
  reactions: Reaction[];
}

export interface UpsertMemoReactionRequest {
  /** The name of the memo. */
  name: string;
  reaction?: Reaction | undefined;
}

export interface DeleteMemoReactionRequest {
  /**
   * The id of the reaction.
   * Refer to the `Reaction.id`.
   */
  id: number;
}

function createBaseMemo(): Memo {
  return {
    name: "",
    state: 0,
    creator: "",
    createTime: undefined,
    updateTime: undefined,
    displayTime: undefined,
    content: "",
    nodes: [],
    visibility: 0,
    tags: [],
    pinned: false,
    resources: [],
    relations: [],
    reactions: [],
    property: undefined,
    parent: undefined,
    snippet: "",
    location: undefined,
  };
}

export const Memo: MessageFns<Memo> = {
  encode(message: Memo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.state !== 0) {
      writer.uint32(24).int32(message.state);
    }
    if (message.creator !== "") {
      writer.uint32(34).string(message.creator);
    }
    if (message.createTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createTime), writer.uint32(42).fork()).join();
    }
    if (message.updateTime !== undefined) {
      Timestamp.encode(toTimestamp(message.updateTime), writer.uint32(50).fork()).join();
    }
    if (message.displayTime !== undefined) {
      Timestamp.encode(toTimestamp(message.displayTime), writer.uint32(58).fork()).join();
    }
    if (message.content !== "") {
      writer.uint32(66).string(message.content);
    }
    for (const v of message.nodes) {
      Node.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.visibility !== 0) {
      writer.uint32(80).int32(message.visibility);
    }
    for (const v of message.tags) {
      writer.uint32(90).string(v!);
    }
    if (message.pinned !== false) {
      writer.uint32(96).bool(message.pinned);
    }
    for (const v of message.resources) {
      Resource.encode(v!, writer.uint32(114).fork()).join();
    }
    for (const v of message.relations) {
      MemoRelation.encode(v!, writer.uint32(122).fork()).join();
    }
    for (const v of message.reactions) {
      Reaction.encode(v!, writer.uint32(130).fork()).join();
    }
    if (message.property !== undefined) {
      Memo_Property.encode(message.property, writer.uint32(138).fork()).join();
    }
    if (message.parent !== undefined) {
      writer.uint32(146).string(message.parent);
    }
    if (message.snippet !== "") {
      writer.uint32(154).string(message.snippet);
    }
    if (message.location !== undefined) {
      Location.encode(message.location, writer.uint32(162).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Memo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.updateTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.displayTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.nodes.push(Node.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.visibility = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.pinned = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.resources.push(Resource.decode(reader, reader.uint32()));
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.relations.push(MemoRelation.decode(reader, reader.uint32()));
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.reactions.push(Reaction.decode(reader, reader.uint32()));
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.property = Memo_Property.decode(reader, reader.uint32());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.snippet = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.location = Location.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Memo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      state: isSet(object.state) ? stateFromJSON(object.state) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      createTime: isSet(object.createTime) ? fromJsonTimestamp(object.createTime) : undefined,
      updateTime: isSet(object.updateTime) ? fromJsonTimestamp(object.updateTime) : undefined,
      displayTime: isSet(object.displayTime) ? fromJsonTimestamp(object.displayTime) : undefined,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      nodes: globalThis.Array.isArray(object?.nodes) ? object.nodes.map((e: any) => Node.fromJSON(e)) : [],
      visibility: isSet(object.visibility) ? visibilityFromJSON(object.visibility) : 0,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      pinned: isSet(object.pinned) ? globalThis.Boolean(object.pinned) : false,
      resources: globalThis.Array.isArray(object?.resources)
        ? object.resources.map((e: any) => Resource.fromJSON(e))
        : [],
      relations: globalThis.Array.isArray(object?.relations)
        ? object.relations.map((e: any) => MemoRelation.fromJSON(e))
        : [],
      reactions: globalThis.Array.isArray(object?.reactions)
        ? object.reactions.map((e: any) => Reaction.fromJSON(e))
        : [],
      property: isSet(object.property) ? Memo_Property.fromJSON(object.property) : undefined,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : undefined,
      snippet: isSet(object.snippet) ? globalThis.String(object.snippet) : "",
      location: isSet(object.location) ? Location.fromJSON(object.location) : undefined,
    };
  },

  toJSON(message: Memo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.state !== 0) {
      obj.state = stateToJSON(message.state);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.createTime !== undefined) {
      obj.createTime = message.createTime.toISOString();
    }
    if (message.updateTime !== undefined) {
      obj.updateTime = message.updateTime.toISOString();
    }
    if (message.displayTime !== undefined) {
      obj.displayTime = message.displayTime.toISOString();
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => Node.toJSON(e));
    }
    if (message.visibility !== 0) {
      obj.visibility = visibilityToJSON(message.visibility);
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.pinned !== false) {
      obj.pinned = message.pinned;
    }
    if (message.resources?.length) {
      obj.resources = message.resources.map((e) => Resource.toJSON(e));
    }
    if (message.relations?.length) {
      obj.relations = message.relations.map((e) => MemoRelation.toJSON(e));
    }
    if (message.reactions?.length) {
      obj.reactions = message.reactions.map((e) => Reaction.toJSON(e));
    }
    if (message.property !== undefined) {
      obj.property = Memo_Property.toJSON(message.property);
    }
    if (message.parent !== undefined) {
      obj.parent = message.parent;
    }
    if (message.snippet !== "") {
      obj.snippet = message.snippet;
    }
    if (message.location !== undefined) {
      obj.location = Location.toJSON(message.location);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Memo>, I>>(base?: I): Memo {
    return Memo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Memo>, I>>(object: I): Memo {
    const message = createBaseMemo();
    message.name = object.name ?? "";
    message.state = object.state ?? 0;
    message.creator = object.creator ?? "";
    message.createTime = object.createTime ?? undefined;
    message.updateTime = object.updateTime ?? undefined;
    message.displayTime = object.displayTime ?? undefined;
    message.content = object.content ?? "";
    message.nodes = object.nodes?.map((e) => Node.fromPartial(e)) || [];
    message.visibility = object.visibility ?? 0;
    message.tags = object.tags?.map((e) => e) || [];
    message.pinned = object.pinned ?? false;
    message.resources = object.resources?.map((e) => Resource.fromPartial(e)) || [];
    message.relations = object.relations?.map((e) => MemoRelation.fromPartial(e)) || [];
    message.reactions = object.reactions?.map((e) => Reaction.fromPartial(e)) || [];
    message.property = (object.property !== undefined && object.property !== null)
      ? Memo_Property.fromPartial(object.property)
      : undefined;
    message.parent = object.parent ?? undefined;
    message.snippet = object.snippet ?? "";
    message.location = (object.location !== undefined && object.location !== null)
      ? Location.fromPartial(object.location)
      : undefined;
    return message;
  },
};

function createBaseMemo_Property(): Memo_Property {
  return { hasLink: false, hasTaskList: false, hasCode: false, hasIncompleteTasks: false };
}

export const Memo_Property: MessageFns<Memo_Property> = {
  encode(message: Memo_Property, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hasLink !== false) {
      writer.uint32(8).bool(message.hasLink);
    }
    if (message.hasTaskList !== false) {
      writer.uint32(16).bool(message.hasTaskList);
    }
    if (message.hasCode !== false) {
      writer.uint32(24).bool(message.hasCode);
    }
    if (message.hasIncompleteTasks !== false) {
      writer.uint32(32).bool(message.hasIncompleteTasks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Memo_Property {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemo_Property();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hasLink = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hasTaskList = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hasCode = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasIncompleteTasks = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Memo_Property {
    return {
      hasLink: isSet(object.hasLink) ? globalThis.Boolean(object.hasLink) : false,
      hasTaskList: isSet(object.hasTaskList) ? globalThis.Boolean(object.hasTaskList) : false,
      hasCode: isSet(object.hasCode) ? globalThis.Boolean(object.hasCode) : false,
      hasIncompleteTasks: isSet(object.hasIncompleteTasks) ? globalThis.Boolean(object.hasIncompleteTasks) : false,
    };
  },

  toJSON(message: Memo_Property): unknown {
    const obj: any = {};
    if (message.hasLink !== false) {
      obj.hasLink = message.hasLink;
    }
    if (message.hasTaskList !== false) {
      obj.hasTaskList = message.hasTaskList;
    }
    if (message.hasCode !== false) {
      obj.hasCode = message.hasCode;
    }
    if (message.hasIncompleteTasks !== false) {
      obj.hasIncompleteTasks = message.hasIncompleteTasks;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Memo_Property>, I>>(base?: I): Memo_Property {
    return Memo_Property.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Memo_Property>, I>>(object: I): Memo_Property {
    const message = createBaseMemo_Property();
    message.hasLink = object.hasLink ?? false;
    message.hasTaskList = object.hasTaskList ?? false;
    message.hasCode = object.hasCode ?? false;
    message.hasIncompleteTasks = object.hasIncompleteTasks ?? false;
    return message;
  },
};

function createBaseLocation(): Location {
  return { placeholder: "", latitude: 0, longitude: 0 };
}

export const Location: MessageFns<Location> = {
  encode(message: Location, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.placeholder !== "") {
      writer.uint32(10).string(message.placeholder);
    }
    if (message.latitude !== 0) {
      writer.uint32(17).double(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(25).double(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Location {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.placeholder = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.latitude = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.longitude = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Location {
    return {
      placeholder: isSet(object.placeholder) ? globalThis.String(object.placeholder) : "",
      latitude: isSet(object.latitude) ? globalThis.Number(object.latitude) : 0,
      longitude: isSet(object.longitude) ? globalThis.Number(object.longitude) : 0,
    };
  },

  toJSON(message: Location): unknown {
    const obj: any = {};
    if (message.placeholder !== "") {
      obj.placeholder = message.placeholder;
    }
    if (message.latitude !== 0) {
      obj.latitude = message.latitude;
    }
    if (message.longitude !== 0) {
      obj.longitude = message.longitude;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Location>, I>>(base?: I): Location {
    return Location.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Location>, I>>(object: I): Location {
    const message = createBaseLocation();
    message.placeholder = object.placeholder ?? "";
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    return message;
  },
};

function createBaseCreateMemoRequest(): CreateMemoRequest {
  return { memo: undefined };
}

export const CreateMemoRequest: MessageFns<CreateMemoRequest> = {
  encode(message: CreateMemoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memo !== undefined) {
      Memo.encode(message.memo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateMemoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateMemoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memo = Memo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateMemoRequest {
    return { memo: isSet(object.memo) ? Memo.fromJSON(object.memo) : undefined };
  },

  toJSON(message: CreateMemoRequest): unknown {
    const obj: any = {};
    if (message.memo !== undefined) {
      obj.memo = Memo.toJSON(message.memo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateMemoRequest>, I>>(base?: I): CreateMemoRequest {
    return CreateMemoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateMemoRequest>, I>>(object: I): CreateMemoRequest {
    const message = createBaseCreateMemoRequest();
    message.memo = (object.memo !== undefined && object.memo !== null) ? Memo.fromPartial(object.memo) : undefined;
    return message;
  },
};

function createBaseListMemosRequest(): ListMemosRequest {
  return { parent: "", pageSize: 0, pageToken: "", state: 0, sort: "", direction: 0, filter: "", oldFilter: "" };
}

export const ListMemosRequest: MessageFns<ListMemosRequest> = {
  encode(message: ListMemosRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.pageToken !== "") {
      writer.uint32(26).string(message.pageToken);
    }
    if (message.state !== 0) {
      writer.uint32(32).int32(message.state);
    }
    if (message.sort !== "") {
      writer.uint32(42).string(message.sort);
    }
    if (message.direction !== 0) {
      writer.uint32(48).int32(message.direction);
    }
    if (message.filter !== "") {
      writer.uint32(58).string(message.filter);
    }
    if (message.oldFilter !== "") {
      writer.uint32(66).string(message.oldFilter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemosRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemosRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sort = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.direction = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.filter = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.oldFilter = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemosRequest {
    return {
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
      pageToken: isSet(object.pageToken) ? globalThis.String(object.pageToken) : "",
      state: isSet(object.state) ? stateFromJSON(object.state) : 0,
      sort: isSet(object.sort) ? globalThis.String(object.sort) : "",
      direction: isSet(object.direction) ? directionFromJSON(object.direction) : 0,
      filter: isSet(object.filter) ? globalThis.String(object.filter) : "",
      oldFilter: isSet(object.oldFilter) ? globalThis.String(object.oldFilter) : "",
    };
  },

  toJSON(message: ListMemosRequest): unknown {
    const obj: any = {};
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.pageToken !== "") {
      obj.pageToken = message.pageToken;
    }
    if (message.state !== 0) {
      obj.state = stateToJSON(message.state);
    }
    if (message.sort !== "") {
      obj.sort = message.sort;
    }
    if (message.direction !== 0) {
      obj.direction = directionToJSON(message.direction);
    }
    if (message.filter !== "") {
      obj.filter = message.filter;
    }
    if (message.oldFilter !== "") {
      obj.oldFilter = message.oldFilter;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemosRequest>, I>>(base?: I): ListMemosRequest {
    return ListMemosRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemosRequest>, I>>(object: I): ListMemosRequest {
    const message = createBaseListMemosRequest();
    message.parent = object.parent ?? "";
    message.pageSize = object.pageSize ?? 0;
    message.pageToken = object.pageToken ?? "";
    message.state = object.state ?? 0;
    message.sort = object.sort ?? "";
    message.direction = object.direction ?? 0;
    message.filter = object.filter ?? "";
    message.oldFilter = object.oldFilter ?? "";
    return message;
  },
};

function createBaseListMemosResponse(): ListMemosResponse {
  return { memos: [], nextPageToken: "" };
}

export const ListMemosResponse: MessageFns<ListMemosResponse> = {
  encode(message: ListMemosResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.memos) {
      Memo.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemosResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemosResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memos.push(Memo.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemosResponse {
    return {
      memos: globalThis.Array.isArray(object?.memos) ? object.memos.map((e: any) => Memo.fromJSON(e)) : [],
      nextPageToken: isSet(object.nextPageToken) ? globalThis.String(object.nextPageToken) : "",
    };
  },

  toJSON(message: ListMemosResponse): unknown {
    const obj: any = {};
    if (message.memos?.length) {
      obj.memos = message.memos.map((e) => Memo.toJSON(e));
    }
    if (message.nextPageToken !== "") {
      obj.nextPageToken = message.nextPageToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemosResponse>, I>>(base?: I): ListMemosResponse {
    return ListMemosResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemosResponse>, I>>(object: I): ListMemosResponse {
    const message = createBaseListMemosResponse();
    message.memos = object.memos?.map((e) => Memo.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    return message;
  },
};

function createBaseGetMemoRequest(): GetMemoRequest {
  return { name: "" };
}

export const GetMemoRequest: MessageFns<GetMemoRequest> = {
  encode(message: GetMemoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMemoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMemoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMemoRequest {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: GetMemoRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMemoRequest>, I>>(base?: I): GetMemoRequest {
    return GetMemoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMemoRequest>, I>>(object: I): GetMemoRequest {
    const message = createBaseGetMemoRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseUpdateMemoRequest(): UpdateMemoRequest {
  return { memo: undefined, updateMask: undefined };
}

export const UpdateMemoRequest: MessageFns<UpdateMemoRequest> = {
  encode(message: UpdateMemoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memo !== undefined) {
      Memo.encode(message.memo, writer.uint32(10).fork()).join();
    }
    if (message.updateMask !== undefined) {
      FieldMask.encode(FieldMask.wrap(message.updateMask), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMemoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMemoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memo = Memo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateMask = FieldMask.unwrap(FieldMask.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMemoRequest {
    return {
      memo: isSet(object.memo) ? Memo.fromJSON(object.memo) : undefined,
      updateMask: isSet(object.updateMask) ? FieldMask.unwrap(FieldMask.fromJSON(object.updateMask)) : undefined,
    };
  },

  toJSON(message: UpdateMemoRequest): unknown {
    const obj: any = {};
    if (message.memo !== undefined) {
      obj.memo = Memo.toJSON(message.memo);
    }
    if (message.updateMask !== undefined) {
      obj.updateMask = FieldMask.toJSON(FieldMask.wrap(message.updateMask));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMemoRequest>, I>>(base?: I): UpdateMemoRequest {
    return UpdateMemoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMemoRequest>, I>>(object: I): UpdateMemoRequest {
    const message = createBaseUpdateMemoRequest();
    message.memo = (object.memo !== undefined && object.memo !== null) ? Memo.fromPartial(object.memo) : undefined;
    message.updateMask = object.updateMask ?? undefined;
    return message;
  },
};

function createBaseDeleteMemoRequest(): DeleteMemoRequest {
  return { name: "" };
}

export const DeleteMemoRequest: MessageFns<DeleteMemoRequest> = {
  encode(message: DeleteMemoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMemoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMemoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteMemoRequest {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: DeleteMemoRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteMemoRequest>, I>>(base?: I): DeleteMemoRequest {
    return DeleteMemoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteMemoRequest>, I>>(object: I): DeleteMemoRequest {
    const message = createBaseDeleteMemoRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseRenameMemoTagRequest(): RenameMemoTagRequest {
  return { parent: "", oldTag: "", newTag: "" };
}

export const RenameMemoTagRequest: MessageFns<RenameMemoTagRequest> = {
  encode(message: RenameMemoTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.oldTag !== "") {
      writer.uint32(18).string(message.oldTag);
    }
    if (message.newTag !== "") {
      writer.uint32(26).string(message.newTag);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RenameMemoTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRenameMemoTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.oldTag = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newTag = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RenameMemoTagRequest {
    return {
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
      oldTag: isSet(object.oldTag) ? globalThis.String(object.oldTag) : "",
      newTag: isSet(object.newTag) ? globalThis.String(object.newTag) : "",
    };
  },

  toJSON(message: RenameMemoTagRequest): unknown {
    const obj: any = {};
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    if (message.oldTag !== "") {
      obj.oldTag = message.oldTag;
    }
    if (message.newTag !== "") {
      obj.newTag = message.newTag;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RenameMemoTagRequest>, I>>(base?: I): RenameMemoTagRequest {
    return RenameMemoTagRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RenameMemoTagRequest>, I>>(object: I): RenameMemoTagRequest {
    const message = createBaseRenameMemoTagRequest();
    message.parent = object.parent ?? "";
    message.oldTag = object.oldTag ?? "";
    message.newTag = object.newTag ?? "";
    return message;
  },
};

function createBaseDeleteMemoTagRequest(): DeleteMemoTagRequest {
  return { parent: "", tag: "", deleteRelatedMemos: false };
}

export const DeleteMemoTagRequest: MessageFns<DeleteMemoTagRequest> = {
  encode(message: DeleteMemoTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.tag !== "") {
      writer.uint32(18).string(message.tag);
    }
    if (message.deleteRelatedMemos !== false) {
      writer.uint32(24).bool(message.deleteRelatedMemos);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMemoTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMemoTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tag = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.deleteRelatedMemos = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteMemoTagRequest {
    return {
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
      tag: isSet(object.tag) ? globalThis.String(object.tag) : "",
      deleteRelatedMemos: isSet(object.deleteRelatedMemos) ? globalThis.Boolean(object.deleteRelatedMemos) : false,
    };
  },

  toJSON(message: DeleteMemoTagRequest): unknown {
    const obj: any = {};
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    if (message.tag !== "") {
      obj.tag = message.tag;
    }
    if (message.deleteRelatedMemos !== false) {
      obj.deleteRelatedMemos = message.deleteRelatedMemos;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteMemoTagRequest>, I>>(base?: I): DeleteMemoTagRequest {
    return DeleteMemoTagRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteMemoTagRequest>, I>>(object: I): DeleteMemoTagRequest {
    const message = createBaseDeleteMemoTagRequest();
    message.parent = object.parent ?? "";
    message.tag = object.tag ?? "";
    message.deleteRelatedMemos = object.deleteRelatedMemos ?? false;
    return message;
  },
};

function createBaseSetMemoResourcesRequest(): SetMemoResourcesRequest {
  return { name: "", resources: [] };
}

export const SetMemoResourcesRequest: MessageFns<SetMemoResourcesRequest> = {
  encode(message: SetMemoResourcesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.resources) {
      Resource.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetMemoResourcesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetMemoResourcesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resources.push(Resource.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetMemoResourcesRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      resources: globalThis.Array.isArray(object?.resources)
        ? object.resources.map((e: any) => Resource.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SetMemoResourcesRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.resources?.length) {
      obj.resources = message.resources.map((e) => Resource.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMemoResourcesRequest>, I>>(base?: I): SetMemoResourcesRequest {
    return SetMemoResourcesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMemoResourcesRequest>, I>>(object: I): SetMemoResourcesRequest {
    const message = createBaseSetMemoResourcesRequest();
    message.name = object.name ?? "";
    message.resources = object.resources?.map((e) => Resource.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListMemoResourcesRequest(): ListMemoResourcesRequest {
  return { name: "" };
}

export const ListMemoResourcesRequest: MessageFns<ListMemoResourcesRequest> = {
  encode(message: ListMemoResourcesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemoResourcesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemoResourcesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemoResourcesRequest {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: ListMemoResourcesRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemoResourcesRequest>, I>>(base?: I): ListMemoResourcesRequest {
    return ListMemoResourcesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemoResourcesRequest>, I>>(object: I): ListMemoResourcesRequest {
    const message = createBaseListMemoResourcesRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseListMemoResourcesResponse(): ListMemoResourcesResponse {
  return { resources: [] };
}

export const ListMemoResourcesResponse: MessageFns<ListMemoResourcesResponse> = {
  encode(message: ListMemoResourcesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.resources) {
      Resource.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemoResourcesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemoResourcesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resources.push(Resource.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemoResourcesResponse {
    return {
      resources: globalThis.Array.isArray(object?.resources)
        ? object.resources.map((e: any) => Resource.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListMemoResourcesResponse): unknown {
    const obj: any = {};
    if (message.resources?.length) {
      obj.resources = message.resources.map((e) => Resource.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemoResourcesResponse>, I>>(base?: I): ListMemoResourcesResponse {
    return ListMemoResourcesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemoResourcesResponse>, I>>(object: I): ListMemoResourcesResponse {
    const message = createBaseListMemoResourcesResponse();
    message.resources = object.resources?.map((e) => Resource.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMemoRelation(): MemoRelation {
  return { memo: undefined, relatedMemo: undefined, type: 0 };
}

export const MemoRelation: MessageFns<MemoRelation> = {
  encode(message: MemoRelation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memo !== undefined) {
      MemoRelation_Memo.encode(message.memo, writer.uint32(10).fork()).join();
    }
    if (message.relatedMemo !== undefined) {
      MemoRelation_Memo.encode(message.relatedMemo, writer.uint32(18).fork()).join();
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MemoRelation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemoRelation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memo = MemoRelation_Memo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.relatedMemo = MemoRelation_Memo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MemoRelation {
    return {
      memo: isSet(object.memo) ? MemoRelation_Memo.fromJSON(object.memo) : undefined,
      relatedMemo: isSet(object.relatedMemo) ? MemoRelation_Memo.fromJSON(object.relatedMemo) : undefined,
      type: isSet(object.type) ? memoRelation_TypeFromJSON(object.type) : 0,
    };
  },

  toJSON(message: MemoRelation): unknown {
    const obj: any = {};
    if (message.memo !== undefined) {
      obj.memo = MemoRelation_Memo.toJSON(message.memo);
    }
    if (message.relatedMemo !== undefined) {
      obj.relatedMemo = MemoRelation_Memo.toJSON(message.relatedMemo);
    }
    if (message.type !== 0) {
      obj.type = memoRelation_TypeToJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MemoRelation>, I>>(base?: I): MemoRelation {
    return MemoRelation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MemoRelation>, I>>(object: I): MemoRelation {
    const message = createBaseMemoRelation();
    message.memo = (object.memo !== undefined && object.memo !== null)
      ? MemoRelation_Memo.fromPartial(object.memo)
      : undefined;
    message.relatedMemo = (object.relatedMemo !== undefined && object.relatedMemo !== null)
      ? MemoRelation_Memo.fromPartial(object.relatedMemo)
      : undefined;
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseMemoRelation_Memo(): MemoRelation_Memo {
  return { name: "", uid: "", snippet: "" };
}

export const MemoRelation_Memo: MessageFns<MemoRelation_Memo> = {
  encode(message: MemoRelation_Memo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.uid !== "") {
      writer.uint32(18).string(message.uid);
    }
    if (message.snippet !== "") {
      writer.uint32(26).string(message.snippet);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MemoRelation_Memo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemoRelation_Memo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.snippet = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MemoRelation_Memo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      uid: isSet(object.uid) ? globalThis.String(object.uid) : "",
      snippet: isSet(object.snippet) ? globalThis.String(object.snippet) : "",
    };
  },

  toJSON(message: MemoRelation_Memo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    if (message.snippet !== "") {
      obj.snippet = message.snippet;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MemoRelation_Memo>, I>>(base?: I): MemoRelation_Memo {
    return MemoRelation_Memo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MemoRelation_Memo>, I>>(object: I): MemoRelation_Memo {
    const message = createBaseMemoRelation_Memo();
    message.name = object.name ?? "";
    message.uid = object.uid ?? "";
    message.snippet = object.snippet ?? "";
    return message;
  },
};

function createBaseSetMemoRelationsRequest(): SetMemoRelationsRequest {
  return { name: "", relations: [] };
}

export const SetMemoRelationsRequest: MessageFns<SetMemoRelationsRequest> = {
  encode(message: SetMemoRelationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.relations) {
      MemoRelation.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetMemoRelationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetMemoRelationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.relations.push(MemoRelation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetMemoRelationsRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      relations: globalThis.Array.isArray(object?.relations)
        ? object.relations.map((e: any) => MemoRelation.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SetMemoRelationsRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.relations?.length) {
      obj.relations = message.relations.map((e) => MemoRelation.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMemoRelationsRequest>, I>>(base?: I): SetMemoRelationsRequest {
    return SetMemoRelationsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMemoRelationsRequest>, I>>(object: I): SetMemoRelationsRequest {
    const message = createBaseSetMemoRelationsRequest();
    message.name = object.name ?? "";
    message.relations = object.relations?.map((e) => MemoRelation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListMemoRelationsRequest(): ListMemoRelationsRequest {
  return { name: "" };
}

export const ListMemoRelationsRequest: MessageFns<ListMemoRelationsRequest> = {
  encode(message: ListMemoRelationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemoRelationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemoRelationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemoRelationsRequest {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: ListMemoRelationsRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemoRelationsRequest>, I>>(base?: I): ListMemoRelationsRequest {
    return ListMemoRelationsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemoRelationsRequest>, I>>(object: I): ListMemoRelationsRequest {
    const message = createBaseListMemoRelationsRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseListMemoRelationsResponse(): ListMemoRelationsResponse {
  return { relations: [] };
}

export const ListMemoRelationsResponse: MessageFns<ListMemoRelationsResponse> = {
  encode(message: ListMemoRelationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.relations) {
      MemoRelation.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemoRelationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemoRelationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.relations.push(MemoRelation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemoRelationsResponse {
    return {
      relations: globalThis.Array.isArray(object?.relations)
        ? object.relations.map((e: any) => MemoRelation.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListMemoRelationsResponse): unknown {
    const obj: any = {};
    if (message.relations?.length) {
      obj.relations = message.relations.map((e) => MemoRelation.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemoRelationsResponse>, I>>(base?: I): ListMemoRelationsResponse {
    return ListMemoRelationsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemoRelationsResponse>, I>>(object: I): ListMemoRelationsResponse {
    const message = createBaseListMemoRelationsResponse();
    message.relations = object.relations?.map((e) => MemoRelation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListMemoReactionsRequest(): ListMemoReactionsRequest {
  return { name: "" };
}

export const ListMemoReactionsRequest: MessageFns<ListMemoReactionsRequest> = {
  encode(message: ListMemoReactionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemoReactionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemoReactionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemoReactionsRequest {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: ListMemoReactionsRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemoReactionsRequest>, I>>(base?: I): ListMemoReactionsRequest {
    return ListMemoReactionsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemoReactionsRequest>, I>>(object: I): ListMemoReactionsRequest {
    const message = createBaseListMemoReactionsRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseListMemoReactionsResponse(): ListMemoReactionsResponse {
  return { reactions: [] };
}

export const ListMemoReactionsResponse: MessageFns<ListMemoReactionsResponse> = {
  encode(message: ListMemoReactionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.reactions) {
      Reaction.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMemoReactionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMemoReactionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reactions.push(Reaction.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListMemoReactionsResponse {
    return {
      reactions: globalThis.Array.isArray(object?.reactions)
        ? object.reactions.map((e: any) => Reaction.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListMemoReactionsResponse): unknown {
    const obj: any = {};
    if (message.reactions?.length) {
      obj.reactions = message.reactions.map((e) => Reaction.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMemoReactionsResponse>, I>>(base?: I): ListMemoReactionsResponse {
    return ListMemoReactionsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMemoReactionsResponse>, I>>(object: I): ListMemoReactionsResponse {
    const message = createBaseListMemoReactionsResponse();
    message.reactions = object.reactions?.map((e) => Reaction.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpsertMemoReactionRequest(): UpsertMemoReactionRequest {
  return { name: "", reaction: undefined };
}

export const UpsertMemoReactionRequest: MessageFns<UpsertMemoReactionRequest> = {
  encode(message: UpsertMemoReactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.reaction !== undefined) {
      Reaction.encode(message.reaction, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpsertMemoReactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpsertMemoReactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reaction = Reaction.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpsertMemoReactionRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      reaction: isSet(object.reaction) ? Reaction.fromJSON(object.reaction) : undefined,
    };
  },

  toJSON(message: UpsertMemoReactionRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.reaction !== undefined) {
      obj.reaction = Reaction.toJSON(message.reaction);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpsertMemoReactionRequest>, I>>(base?: I): UpsertMemoReactionRequest {
    return UpsertMemoReactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpsertMemoReactionRequest>, I>>(object: I): UpsertMemoReactionRequest {
    const message = createBaseUpsertMemoReactionRequest();
    message.name = object.name ?? "";
    message.reaction = (object.reaction !== undefined && object.reaction !== null)
      ? Reaction.fromPartial(object.reaction)
      : undefined;
    return message;
  },
};

function createBaseDeleteMemoReactionRequest(): DeleteMemoReactionRequest {
  return { id: 0 };
}

export const DeleteMemoReactionRequest: MessageFns<DeleteMemoReactionRequest> = {
  encode(message: DeleteMemoReactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMemoReactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMemoReactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteMemoReactionRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: DeleteMemoReactionRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteMemoReactionRequest>, I>>(base?: I): DeleteMemoReactionRequest {
    return DeleteMemoReactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteMemoReactionRequest>, I>>(object: I): DeleteMemoReactionRequest {
    const message = createBaseDeleteMemoReactionRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

export interface MemoService {
  /** CreateMemo creates a memo. */
  CreateMemo(request: CreateMemoRequest): Promise<Memo>;
  /** ListMemos lists memos with pagination and filter. */
  ListMemos(request: ListMemosRequest): Promise<ListMemosResponse>;
  /** GetMemo gets a memo. */
  GetMemo(request: GetMemoRequest): Promise<Memo>;
  /** UpdateMemo updates a memo. */
  UpdateMemo(request: UpdateMemoRequest): Promise<Memo>;
  /** DeleteMemo deletes a memo. */
  DeleteMemo(request: DeleteMemoRequest): Promise<Empty>;
  /** RenameMemoTag renames a tag for a memo. */
  RenameMemoTag(request: RenameMemoTagRequest): Promise<Empty>;
  /** DeleteMemoTag deletes a tag for a memo. */
  DeleteMemoTag(request: DeleteMemoTagRequest): Promise<Empty>;
  /** SetMemoResources sets resources for a memo. */
  SetMemoResources(request: SetMemoResourcesRequest): Promise<Empty>;
  /** ListMemoResources lists resources for a memo. */
  ListMemoResources(request: ListMemoResourcesRequest): Promise<ListMemoResourcesResponse>;
  /** SetMemoRelations sets relations for a memo. */
  SetMemoRelations(request: SetMemoRelationsRequest): Promise<Empty>;
  /** ListMemoRelations lists relations for a memo. */
  ListMemoRelations(request: ListMemoRelationsRequest): Promise<ListMemoRelationsResponse>;
  /** ListMemoReactions lists reactions for a memo. */
  ListMemoReactions(request: ListMemoReactionsRequest): Promise<ListMemoReactionsResponse>;
  /** UpsertMemoReaction upserts a reaction for a memo. */
  UpsertMemoReaction(request: UpsertMemoReactionRequest): Promise<Reaction>;
  /** DeleteMemoReaction deletes a reaction for a memo. */
  DeleteMemoReaction(request: DeleteMemoReactionRequest): Promise<Empty>;
}

export const MemoServiceServiceName = "memos.api.v1.MemoService";
export class MemoServiceClientImpl implements MemoService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MemoServiceServiceName;
    this.rpc = rpc;
    this.CreateMemo = this.CreateMemo.bind(this);
    this.ListMemos = this.ListMemos.bind(this);
    this.GetMemo = this.GetMemo.bind(this);
    this.UpdateMemo = this.UpdateMemo.bind(this);
    this.DeleteMemo = this.DeleteMemo.bind(this);
    this.RenameMemoTag = this.RenameMemoTag.bind(this);
    this.DeleteMemoTag = this.DeleteMemoTag.bind(this);
    this.SetMemoResources = this.SetMemoResources.bind(this);
    this.ListMemoResources = this.ListMemoResources.bind(this);
    this.SetMemoRelations = this.SetMemoRelations.bind(this);
    this.ListMemoRelations = this.ListMemoRelations.bind(this);
    this.ListMemoReactions = this.ListMemoReactions.bind(this);
    this.UpsertMemoReaction = this.UpsertMemoReaction.bind(this);
    this.DeleteMemoReaction = this.DeleteMemoReaction.bind(this);
  }
  CreateMemo(request: CreateMemoRequest): Promise<Memo> {
    const data = CreateMemoRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateMemo", data);
    return promise.then((data) => Memo.decode(new BinaryReader(data)));
  }

  ListMemos(request: ListMemosRequest): Promise<ListMemosResponse> {
    const data = ListMemosRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListMemos", data);
    return promise.then((data) => ListMemosResponse.decode(new BinaryReader(data)));
  }

  GetMemo(request: GetMemoRequest): Promise<Memo> {
    const data = GetMemoRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetMemo", data);
    return promise.then((data) => Memo.decode(new BinaryReader(data)));
  }

  UpdateMemo(request: UpdateMemoRequest): Promise<Memo> {
    const data = UpdateMemoRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateMemo", data);
    return promise.then((data) => Memo.decode(new BinaryReader(data)));
  }

  DeleteMemo(request: DeleteMemoRequest): Promise<Empty> {
    const data = DeleteMemoRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteMemo", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  RenameMemoTag(request: RenameMemoTagRequest): Promise<Empty> {
    const data = RenameMemoTagRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RenameMemoTag", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  DeleteMemoTag(request: DeleteMemoTagRequest): Promise<Empty> {
    const data = DeleteMemoTagRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteMemoTag", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  SetMemoResources(request: SetMemoResourcesRequest): Promise<Empty> {
    const data = SetMemoResourcesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetMemoResources", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  ListMemoResources(request: ListMemoResourcesRequest): Promise<ListMemoResourcesResponse> {
    const data = ListMemoResourcesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListMemoResources", data);
    return promise.then((data) => ListMemoResourcesResponse.decode(new BinaryReader(data)));
  }

  SetMemoRelations(request: SetMemoRelationsRequest): Promise<Empty> {
    const data = SetMemoRelationsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetMemoRelations", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  ListMemoRelations(request: ListMemoRelationsRequest): Promise<ListMemoRelationsResponse> {
    const data = ListMemoRelationsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListMemoRelations", data);
    return promise.then((data) => ListMemoRelationsResponse.decode(new BinaryReader(data)));
  }

  ListMemoReactions(request: ListMemoReactionsRequest): Promise<ListMemoReactionsResponse> {
    const data = ListMemoReactionsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListMemoReactions", data);
    return promise.then((data) => ListMemoReactionsResponse.decode(new BinaryReader(data)));
  }

  UpsertMemoReaction(request: UpsertMemoReactionRequest): Promise<Reaction> {
    const data = UpsertMemoReactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpsertMemoReaction", data);
    return promise.then((data) => Reaction.decode(new BinaryReader(data)));
  }

  DeleteMemoReaction(request: DeleteMemoReactionRequest): Promise<Empty> {
    const data = DeleteMemoReactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteMemoReaction", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
